### ISSUE TITLE
Iterative solver counter example generation bug. 

### ISSUE THREAD

**Issue by taegyunkim** [chipmunk-project/chipmunk#102]
Run `python3 tests/test_chipmunk.py IterativeSolverTest.test_sampling_revised_2_2_raw_cex_mode`

Then open `sampling_revised_raw_2_2_codegen_iteration_2.sk`. 
The file contains 
```C
  |StateAndPacket| x_1_2 = |StateAndPacket|(
pkt_0 = 4,
state_group_0_state_00 = 4,
state_group_0_state_01 = 4,
state_group_0_state_02 = 4,
state_group_0_state_03 = 4,
state_group_0_state_04 = 4,
```

Open `sampling_revised_raw_2_2_codegen_iteration_2_output.txt`

```
    --slv-randassign              Concretize high-impact holes.
SKETCH version 1.7.5
Benchmark = sampling_revised_raw_2_2_codegen_iteration_2.sk
    ^[[0;32m[1556415441.2170 - DEBUG] Running stage 'parse' -- Parse the program from a file^[[0m
    ^[[0;31m[1556415441.4000 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_0_state_00 (at samplin..tion_2.sk:694)^[[0m
    ^[[0;31m[1556415441.4010 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_0_state_00 (at samplin..tion_2.sk:708)^[[0m
    ^[[0;31m[1556415441.4011 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_0_state_00 (at samplin..tion_2.sk:716)^[[0m
    ^[[0;31m[1556415441.4012 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_0_state_00 (at samplin..tion_2.sk:724)^[[0m
    ^[[0;31m[1556415441.4020 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_0_state_00 (at samplin..tion_2.sk:732)^[[0m
    ^[[0;31m[1556415441.4021 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_0_state_00 (at samplin..tion_2.sk:740)^[[0m
    ^[[0;31m[1556415441.4150 - ERROR] [SKETCH] Program Parse Error: Semantic check failed^[[0m
    ^[[0;32m[1556415441.4160 - DEBUG] [SKETCH] stack trace written to file: /home/taegyunk/.sketch/tmp/stacktrace.txt^[[0m
Total time = 265
Command exited with non-zero status 1
1.14user 0.22system 0:00.39elapsed 346%CPU (0avgtext+0avgdata 80872maxresident)k
0inputs+72outputs (0major+17438minor)pagefaults 0swaps
```

**Comment by taegyunkim** [comment]
Noticed this while working on #98, should be fixed by #98.

**Comment by anirudhSK** [comment]
How did this happen in the first place? The last integer in state_group_0_state_* should be 0, 1, 2, 3, ... Not 00, 01, ...

**Comment by taegyunkim** [comment]
This line https://github.com/chipmunk-project/chipmunk/blob/master/chipc/iterative_solver.py#L59

**Comment by anirudhSK** [comment]
Which commit introduced it and how come we couldn't catch it in our tests?

**Comment by taegyunkim** [comment]
https://github.com/chipmunk-project/chipmunk/commit/1d5eba7bdc11676e9df388af64b5d50c7b85ba13

Our tests are very limited and most of them only check return value, not the intermediary outputs.

**Comment by anirudhSK** [comment]
OK. That branch of the code kicks in when the counter examples that are generated do not include every state variable (because some versions of Sketch optimize them away). Now that we are using z3 for counter examples hopefully we can remove that code branch. At the same time, can we assert that the counter examples generated by z3 does contain every state variable or packet field?
