### ISSUE TITLE
Add nonnegative restriction in .smt2 file

### ISSUE THREAD

**Issue by XiangyuG** [chipmunk-project/chipmunk#108]
In our chipmunk project, we can guarantee all the inputs(packet vars and stateful vars are nonnegative),  so the file z3_without_bound only mean the value range can be [0, inf) rather than (-inf,inf).

**Comment by XiangyuG** [comment]
For example:
If(If(False, 1, 0) < pkt_0_5_5_0,
                      state_group_0_state_0_7_7_0 +
                      If(If(False, 1, 0) < pkt_0_5_5_0,
                         pkt_0_5_5_0,
                         If(False, 1, 0)),
                      state_group_0_state_0_7_7_0) ==
                   state_group_0_state_0_7_7_0 + pkt_0_5_5_0)
This will pass in the nonnegative range but failed in R

**Comment by taegyunkim** [comment]
What do you mean by failed in R? 

Btw, what should happen for programs having internal counter variable which could possibly overflow and wrap around to negative values? This might be different problem, but just came into my minds.

**Comment by XiangyuG** [comment]
R means all the real number. (-inf , inf).

Yeah, we can keep the overflow problem in mind

**Comment by XiangyuG** [comment]
BTW, in our example, we only need to consider all integers, so precisely this should be in Z+ area.
