### ISSUE TITLE
Provide a way to limit the number of cores to use

### ISSUE THREAD

**Issue by taegyunkim** [chipmunk-project/chipmunk#122]
two layers of parallelism
1. adaptive concretization: M == number of cores 
2. our parallelism with salu_config: N == (# states) ^ (# state vars)

The total number of threads is N * M
From benchmarks, observed 800 threads for 50 cores
In this case, we would spend much time in context switching
We probably need to fix this issue.

**Comment by taegyunkim** [comment]
cegis and sketch takes up all of cyclops' resources, and I can't use that machine to do other useful stuffs.

**Comment by taegyunkim** [comment]
Even with slv-nativeints this happens quite often.

**Comment by anirudhSK** [comment]
Closing this for now; we haven't been using our parallel mode for a while now. If we use only Sketch's parallel mode, it automatically limits itself to the number of cores on the machine.
