### ISSUE TITLE
Debug "sketch not resolved" error

### ISSUE THREAD

**Issue by anirudhSK** [chipmunk-project/chipmunk#137]
Sketch seems to return success, failure, and not resolved. We need to understand the causes behind the not resolved error message from Sketch.

**Comment by taegyunkim** [comment]
Could you elaborate? Are you referring your 2nd question in [this comment](https://github.com/chipmunk-project/chipmunk/issues/128#issuecomment-500040944)? 

I agree that we need to include more cases in [check_syntax()](https://github.com/chipmunk-project/chipmunk/blob/master/chipc/sketch_utils.py#L4) function.

**Comment by anirudhSK** [comment]
No. This is not a syntax error. Sketch sometimes passes the syntax checks, runs for a non-trivial amount of time, and then terminates with a "Sketch not resolved" error from the Sketch backend. It can happen when it runs out of memory.

**Comment by anirudhSK** [comment]
This mailing list post: https://lists.csail.mit.edu/pipermail/sketchusers/2019-June/000090.html says that "Not resolved" can be because of an unsatisfiable assertion encountered by the SMT solver in the backend. So as far as we are concerned, we should probably just treat it no differently from a failure.
