### ISSUE TITLE
Modify hole-elimination to not add counterexamples for the purpose of comparison

### ISSUE THREAD

**Issue by taegyunkim** [chipmunk-project/chipmunk#143]

**Comment by taegyunkim** [comment]
While working on this, I have found an issue with the way z3 outputting SMT formula. For some runs like this https://ci.appveyor.com/project/anirudhSK/chipmunk-hhg5f/builds/25307296, the smt2 file raises an exception with sort mismatch (type mismatch). 

If I instead use sketch to find counterexamples, it will give right counterexamples, but the corresponding smt2 output file causes that. Somehow, the way sketch output z3 file is wrong. 

I think this issue might happen for any kind of sketch and we have to debug. We can work around this by reverting back to use sketch for verification & counterexample generation.

**Comment by taegyunkim** [comment]
This has been addressed by #145 but some execution might lead to the error mentioned in my previous comment. I asked a question on sketchusers@ mailing list to narrow down the root cause. Leaving this open for now.

**Comment by anirudhSK** [comment]
@taegyunkim: Can you point me to the sketch mailing list post on this issue?
