### ISSUE TITLE
Chipmunk sometimes fails to generate smt2 file.

### ISSUE THREAD

**Issue by XiangyuG** [chipmunk-project/chipmunk#159]
**cmd line**
iterative_solver /tmp/rcp_equivalent_1_canonicalizer_equivalent_0.sk example_alus/stateful_alus/pred_raw.alu example_alus/stateless_alus/stateless_alu.alu 4 4 '{0,1,2,3,30}' 10 --parallel-sketch

**Error message**
Traceback (most recent call last):
  File "/home/xiangyug/.local/bin/iterative_solver", line 9, in <module>
    load_entry_point('chipc', 'console_scripts', 'iterative_solver')()
  File "/home/xiangyug/chipmunk/chipc/iterative_solver.py", line 214, in run_main
    sys.exit(main(sys.argv))
  File "/home/xiangyug/chipmunk/chipc/iterative_solver.py", line 183, in main
    hole_assignments, sol_verify_bit, iter_cnt=count
  File "/home/xiangyug/chipmunk/chipc/compiler.py", line 252, in verify
    return z3_utils.generate_counter_examples(smt2_filename)
  File "/home/xiangyug/chipmunk/chipc/z3_utils.py", line 48, in generate_counter_examples
    formula = parse_smt2_file(smt2_filename)
  File "/home/xiangyug/chipmunk/chipc/z3_utils.py", line 19, in parse_smt2_file
    formulas = z3.parse_smt2_file(smt2_filename)
  File "/home/xiangyug/.local/lib/python3.5/site-packages/z3/z3.py", line 8578, in parse_smt2_file
    return AstVector(Z3_parse_smtlib2_file(ctx.ref(), f, ssz, snames, ssorts, dsz, dnames, ddecls), ctx)
  File "/home/xiangyug/.local/lib/python3.5/site-packages/z3/z3core.py", line 3194, in Z3_parse_smtlib2_file
    _elems.Check(a0)
  File "/home/xiangyug/.local/lib/python3.5/site-packages/z3/z3core.py", line 1373, in Check
    raise self.Exception(self.get_error_message(ctx, err))
z3.z3types.Z3Exception: b'file access error'

**/tmp/rcp_equivalent_1_canonicalizer_equivalent_0.sk**
|StateAndPacket| program (|StateAndPacket| state_and_packet) {
state_and_packet.state_group_0_state_0=state_and_packet.state_group_0_state_0+1-1;
state_and_packet.state_group_1_state_0=state_and_packet.state_group_1_state_0+1-1;
state_and_packet.pkt_0=state_and_packet.pkt_0+1-1;
state_and_packet.pkt_1=state_and_packet.pkt_1+1-1;
state_and_packet.state_group_2_state_0=state_and_packet.state_group_2_state_0+1-1;
if ((state_and_packet.state_group_2_state_0==state_and_packet.state_group_2_state_0+1-1)&&(state_and_packet.state_group_1_state_0==state_and_packet.state_group_1_state_0+1-1)&&(state_and_packet.state_group_0_state_0==state_and_packet.state_group_0_state_0+1-1)&&0==1) {state_and_packet.state_group_0_state_0=0-state_and_packet.state_group_0_state_0;
state_and_packet.state_group_0_state_0=state_and_packet.state_group_0_state_0+1;
state_and_packet.state_group_1_state_0=state_and_packet.state_group_1_state_0+1;
state_and_packet.state_group_2_state_0=state_and_packet.state_group_2_state_0+1;

;}
state_and_packet.state_group_0_state_0=state_and_packet.state_group_0_state_0-1;
state_and_packet.state_group_1_state_0=state_and_packet.state_group_1_state_0-1;
state_and_packet.state_group_2_state_0=state_and_packet.state_group_2_state_0-1;
state_and_packet.state_group_0_state_0+=state_and_packet.pkt_1;
if ((state_and_packet.state_group_2_state_0==state_and_packet.state_group_2_state_0+1-1)&&(state_and_packet.state_group_1_state_0==state_and_packet.state_group_1_state_0+1-1)&&(state_and_packet.state_group_0_state_0==state_and_packet.state_group_0_state_0+1-1)&&1==1&&(state_and_packet.state_group_2_state_0==state_and_packet.state_group_2_state_0+1-1)&&(state_and_packet.state_group_1_state_0==state_and_packet.state_group_1_state_0+1-1)&&(state_and_packet.state_group_0_state_0==state_and_packet.state_group_0_state_0+1-1)&&state_and_packet.pkt_0<30) {state_and_packet.state_group_2_state_0+=state_and_packet.pkt_0;
state_and_packet.state_group_1_state_0+=1;
state_and_packet.state_group_0_state_0=state_and_packet.state_group_0_state_0+1;
state_and_packet.state_group_1_state_0=state_and_packet.state_group_1_state_0+1;
state_and_packet.state_group_2_state_0=state_and_packet.state_group_2_state_0+1;
state_and_packet.state_group_0_state_0=state_and_packet.state_group_0_state_0+1;
state_and_packet.state_group_1_state_0=state_and_packet.state_group_1_state_0+1;
state_and_packet.state_group_2_state_0=state_and_packet.state_group_2_state_0+1;

;}
state_and_packet.state_group_0_state_0=state_and_packet.state_group_0_state_0-1;
state_and_packet.state_group_1_state_0=state_and_packet.state_group_1_state_0-1;
state_and_packet.state_group_2_state_0=state_and_packet.state_group_2_state_0-1;
state_and_packet.state_group_0_state_0=state_and_packet.state_group_0_state_0-1;
state_and_packet.state_group_1_state_0=state_and_packet.state_group_1_state_0-1;
state_and_packet.state_group_2_state_0=state_and_packet.state_group_2_state_0-1;
  return state_and_packet;
}

**Comment by XiangyuG** [comment]
@taegyunkim This error is similar to the error we talked about several days ago in slack which fail to generate smt2 file. Previously, the error is because I fail to pass the constant_set to verify_iter.sk file. 

If you have time, why not we together take a look at this error to fix the potential bug in it.

**Comment by taegyunkim** [comment]
Yeah, the previous error was gone, right? Why don't you take a look at this too and this might be simple to fix too.

**Comment by XiangyuG** [comment]
This is because of the slv-timeout is too short. Just increase it to 0.1 for now.

**Comment by anirudhSK** [comment]
Closing this for now. The long-term fix is to not rely on the writeSMT flag to generate smt2 files and instead dump the Sketch IR and generate the smt2 file ourselves.
