### ISSUE TITLE
Check correctness only on a user-specified set of packet fields.

### ISSUE THREAD

**Issue by anirudhSK** [chipmunk-project/chipmunk#36]
Not all packet fields in the implementation need to match up with the spec. In particular, temporary packet fields don't need to match up. This can provide optimization opportunities.

**Comment by taegyunkim** [comment]
If we look at hull.sk, it has three packet fields, but we're only interested in the `mark`. There needs to be an interface for programmer to specify this when they run chipmunk and we only check the correctness on specified packet fields.

**Comment by taegyunkim** [comment]
Closed by #73
