### ISSUE TITLE
Add a build system.

### ISSUE THREAD

**Issue by anirudhSK** [chipmunk-project/chipmunk#38]
Right now, we need to remember to run antlr4 every time. The build system should do this for us.

**Comment by taegyunkim** [comment]
Even if we have a build system, don't we still have to run, e.g. `make` every time we update the grammar? 
We can modify chipmunk.py to build it everytime it's invoked, but that sounds like an overkill. Do you have any other thought?

**Comment by anirudhSK** [comment]
We do have to run the build system every time we change the grammar. Let's not modify chipmunk.py. The build should produce executables (e.g., chipmunk, repeated_solver, optverify etc.) that we can install into the system and run from anywhere.

**Comment by taegyunkim** [comment]
Acknowledged. 

Btw, the name chipmunk is already taken, https://pypi.org/project/chipmunk/, though we don't need to register this online at this point.

**Comment by taegyunkim** [comment]
Note to self: [setuptools-antlr](https://pypi.org/project/setuptools-antlr/) can be used to auto generate lexers and parsers.

**Comment by anirudhSK** [comment]
Closed in https://github.com/anirudhSK/chipmunk/pull/59
