### ISSUE TITLE
Add some negative tests.

### ISSUE THREAD

**Issue by anirudhSK** [chipmunk-project/chipmunk#41]
For instance, the fact that simple.sk doesn't compile to a 1-by-1 or a 1-by-2 grid.

**Comment by anirudhSK** [comment]
Can we add a few more: test.sk doesn't compile to 3-by-3 grids and below. But it should compile on 4-by-4. Also, can we disable some tests by default? test.sk's tests take more than a minute each.

**Comment by taegyunkim** [comment]
They would be better to be run by default. We wouldn't test them if that's not the case.

**Comment by anirudhSK** [comment]
OK, let's add and run them by default.

**Comment by taegyunkim** [comment]
Do you remember what stateful alu did you use for that?

**Comment by anirudhSK** [comment]
raw. It might fail on others as well.

**Comment by taegyunkim** [comment]
#43 addressed this
