### ISSUE TITLE
Instead of specifying output sketch name, simply generate it from input configs. 

### ISSUE THREAD

**Issue by taegyunkim** [chipmunk-project/chipmunk#44]
For example, given following command
```Shell
python3 chipmunk.py example_specs/simple.sk example_alus/raw.stateful_alu 1 2 codegen simple serial   
```

Generates 
- simple_codegen.sk
- simple.errors oir simple.success 

Instead of doing that and specifying the output sketch name, maybe use following prefix? 
`<program filename>_<alu filename>_<num pipeline stages>_<num alus> `

**Comment by anirudhSK** [comment]
Your comment seems to have gotten cut off. What prefix did you have in mind?

**Comment by taegyunkim** [comment]
Updated the comment.
