### ISSUE TITLE
Tests take too long on @XiangyuG 's 2011 Mid 13-inch Macbook Air

### ISSUE THREAD

**Issue by taegyunkim** [chipmunk-project/chipmunk#53]
For me, it takes about 30 seconds, and I'm using MacBook Pro (15-inch, 2018) with 2.6 GHz Intel Core i7. 

@XiangyuG 's doesn't complete even after 5 minutes. His machine has 1.8Ghz Intel Core i7.

**Comment by taegyunkim** [comment]
@anirudhSK some tests taking too much time might be problematic when we have CI running tests.

**Comment by anirudhSK** [comment]
For now, the CI job takes about 5 to 6 minutes (https://github.com/chipmunk-project/chipmunk/pull/65), which is tolerable. Closing this issue for now.
