### ISSUE TITLE
Visualization for debugging

### ISSUE THREAD

**Issue by taegyunkim** [chipmunk-project/chipmunk#60]
It would be helpful to have a tool to visualize the hole value assignments.

For example, let's say we have an ALU for arithmetic operations like this.

if  (hole == 0) {
  x = x + 1;
} else if (hole == 1) {
  x = x * 2;
} else if (hole == 2) {
  x = x / 3;
}

If the assigned hole value was 2, then it would be nice to fold all the other if/else if clause, and only pretty-print x = x / 3. 

With this functionality we could compare the original program and the sketch?

@XiangyuG Please explain what we discussed more here.

**Comment by XiangyuG** [comment]
The example is quite similar to what Taegyun has mentioned. 

I want to name this process as Visualization of Instruction Set. After successfully running sketch file, we can get a bunch of hole values. Then, we can choose which specific instruction set we want to see from the grid(i.e the second atom in the third stage) and the output will be the "concrete" instruction set(replace ?? with hole values to transfer from general atom to a specific atom).

This is clearer for us to understand the compilation result.

**Comment by anirudhSK** [comment]
@XiangyuG has some preliminary work here: https://github.com/XiangyuG/alu_visualization For now, let's close this.
