### ISSUE TITLE
Formatting is off in some places.

### ISSUE THREAD

**Issue by anirudhSK** [chipmunk-project/chipmunk#76]
https://github.com/chipmunk-project/chipmunk/blob/master/chipc/iterative_solver.py#L123 Maybe there's a way to run yapf before pushing to GitHub so that we don't have to worry about formatting?

**Comment by taegyunkim** [comment]
https://pre-commit.com/

We can set-up pre-commit hooks in a way that a formatter is run for every commit.

**Comment by taegyunkim** [comment]
#90 resolved this.
