### ISSUE TITLE
Look into GitHub security warning (https://github.com/chipmunk-project/chipmunk/network/alert/requirements.txt/Jinja2/open)

### ISSUE THREAD

**Issue by anirudhSK** [chipmunk-project/chipmunk#89]
https://github.com/chipmunk-project/chipmunk/network/alert/requirements.txt/Jinja2/open

**Comment by taegyunkim** [comment]
The page shows 404 error to me.

**Comment by anirudhSK** [comment]
I think this alert is gone now because we deleted requirements.txt. Closing this issue.
