### ISSUE TITLE
Gradual search

### ISSUE THREAD

**Issue by anirudhSK** [chipmunk-project/chipmunk#93]
1. Try out a subset of opcodes for the stateless ALU first before trying out everything.

2. Try out a subset of the stateful ALU's functionality before trying out the full stateful ALU.

We already have stateful ALUs arranged in a hierarchy (raw, pred_raw, if_else_raw, ...). We need to create a similar hierarchy of stateless ALUs.

This way we optimize for the common case where synthesis can complete quickly when a program doesn't need the full expressive power of the ALUs.

**Comment by taegyunkim** [comment]
We also want gradual search on constants for completeness.

**Comment by anirudhSK** [comment]
Subsumed by issue #126
