### ISSUE TITLE
More z3 usages

### ISSUE THREAD

**Issue by taegyunkim** [chipmunk-project/chipmunk#98]
- optverify. 
- counter_example_generator.

**Comment by taegyunkim** [comment]
Note to self: 

Suppose we want to generate a counterexample for ((x > 3) && (x < 2))

Following code snippet works. 

https://rise4fun.com/Z3/55g5
```SMT2
(set-option :produce-proofs true)
(set-option :unsat-core true)
(declare-const x Int)
(assert (not (and (> x 3) (< x 2)) ))
(check-sat)
(get-model)
(eval x)
```

Basically, parse the smt2 file, then declare constants(variables), assert negation, check satisfiability, get model and evaluate the variables.

**Comment by taegyunkim** [comment]
Sketch file for counterexample mode with 4 bits input. 

https://gist.github.com/taegyunkim/87b9f613b98852953b107097c272dced#file-sampling_revised_if_else_raw_3_3_cexgen_iteration_1_bits_4-sk

```
sketch -V 3 --debug-cex --bnd-inbits=4 sampling_revised_if_else_raw_3_3_cexgen_iteration_1_bits_4.sk --beopt:writeSMT cexgen.smt2
...
input state_group_0_state_0_3_3_0 has value 17= (13)
...
```

Original smt2 file output from above run with --beopt:writeSMT option
https://gist.github.com/taegyunkim/87b9f613b98852953b107097c272dced#file-cexgen-smt2

Modified smt2 file to get counterexample. 
https://gist.github.com/taegyunkim/87b9f613b98852953b107097c272dced#file-cexgen_success-smt2
```
$> z3 cexgen_success.smt2
sat
(model
  (define-fun pkt_0_2_2_0 () Int
    0)
  (define-fun state_group_0_state_0_3_3_0 () Int
    13)
)
0
13
```

With original smt2 file this script will also get the counter examples
https://github.com/taegyunkim/chipmunk/blob/z3-cex/z3_code.py
```
$> python3 z3_code.py
...
[pkt_0_2_2_0 = 0, state_group_0_state_0_3_3_0 = 13]
```

**Comment by anirudhSK** [comment]
Let's close this for now. Cex generation is anyway using z3 after PR #139. We can worry about optverify once we actually start working on it regularly.
